version: 2.1

workflows:
  test-and-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master

jobs:
  test:
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-jars-{{ checksum "project.clj" }}
      - run: lein test :unit
      - save_cache:
          key: v1-jars-{{ checksum "project.clj" }}
          paths:
            - /root/.m2
  deploy:
    docker:
      - image: clojure:lein-2.8.1
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            git config --global user.email "sayhi@circleci.com"
            git config --global user.name "CircleCI builder"
      - run:
          name: Deploy JAR
          command: lein deploy
